import Head from "next/head";
import { Portfolio } from "../components/Portfolio";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Portfolio />
    </div>
  );
}
