import Head from "next/head";
import { Navbar } from "../components/Navbar";

export default function Home({toggleTheme }) {
  return (
    <div>
      <Head>
        <title>Next js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Navbar toggletheme={toggleTheme}  />
    </div>
  );
}
